version: "3.5"
services:
  postgres:
    image: postgres
    container_name: dell_postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: dell
      POSTGRES_PASSWORD: dell
      POSTGRES_DB: dell
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.5GB"
